### ISSUE TITLE
Ignoring configuration setting for CQINg

### ISSUE THREAD

**Issue by Toucouleur66** [dg5lp/JTDX-Helper-2.1#5]
I'm a new user here for JTDX Helper and can't say enough thanks for making this tool possible

I tried to configure the whole thing but figured the `Max. CQs before sleep` value is being ignored. In my screenshot, you will see I try to tell JTDX Helper to call CQ 2 times, and "Sleep" for 4 sequence. But so far, it always send 6 CQ sequences instead of 2, then wait for 5 sequence.

It seems to me field named "Max. Broken QSO in S/P cycle" is the value for when JTDX will search/pounce

Additionally what could be great, would be to NOT update the CQ message. If we set something like "CQ DX CALL JN12" it seems JTDX Helper reset message and always use the regular sequence.

Thanks again for your work!

<img width="1508" alt="Capture d’écran 2023-04-10 à 20 01 36" src="https://user-images.githubusercontent.com/75485458/230964543-ffb3e6d9-7af9-4257-8c3f-11bb465ebad3.png">

<img width="1508" alt="Capture d’écran 2023-04-10 à 20 01 46" src="https://user-images.githubusercontent.com/75485458/230964420-9e3afa29-d307-41cf-881d-a7b9b931f148.png">

**Comment by dg5lp** [comment]
The Max.CQ and Sleep values are only used in „pure“ CQ-mode. 

You was in XCHG-mode, as the <-x-> checkbox was checked.

In this mode, switching between CQ and SP is determined by the Max. Broken QSOs in S/P and CQ cycle. No sleep cycle added.

 

If you want call CQ-DX, enter „DX“ into the GenMsg CQ-field. (or any other CQ-extension)

 

Please note, that external programs especially those changeng the characters of JTDX may have bad impact on the

function of the JTDX-Helper

 

DESELECT the „Waned checkbox“ in JTDX. It will not work!! Use the wanted and exlcude list in the JTDX-Helper only. 

 

Check github for new versions.   In some day I will upload a new version.

 

 

Von: Toucouleur66 ***@***.*** 
Gesendet: Montag, 10. April 2023 20:14
An: dg5lp/JTDX-Helper-2.6
Cc: Subscribed
Betreff: [dg5lp/JTDX-Helper-2.6] Ignoring configuration setting for CQINg (Issue #5)

 

I'm a new user here for JTDX Helper and can't say enough thanks for making this tool possible

I tried to configure the whole thing but figured the Max. CQs before sleep value is being ignored. In my screenshot, you will see I try to tell JTDX Helper to call CQ 2 times, and "Sleep" for 4 sequence. But so far, it always send 6 CQ sequences instead of 2, then wait for 5 sequence.

It seems to me field named "Max. Broken QSO in S/P cycle" is the value for when JTDX will search/pounce

Additionally what could be great, would be to NOT update the CQ message. If we set something like "CQ DX CALL JN12" it seems JTDX Helper reset message and always use the regular sequence.

Thanks again for your work!

 <https://user-images.githubusercontent.com/75485458/230964543-ffb3e6d9-7af9-4257-8c3f-11bb465ebad3.png> Das Bild wurde vom Absender entfernt. Capture d’écran 2023-04-10 à 20 01 36

 <https://user-images.githubusercontent.com/75485458/230964420-9e3afa29-d307-41cf-881d-a7b9b931f148.png> Das Bild wurde vom Absender entfernt. Capture d’écran 2023-04-10 à 20 01 46

**Comment by Toucouleur66** [comment]
No additional program for font changes, only I change the size of font within JTDX program

Thanks for all your answers, I keep in mind to remove the wanted checkbox within JTDX

Thanks again for your outstanding work
