### ISSUE TITLE
Set frequency instead of band while using band hoping

### ISSUE THREAD

**Issue by Toucouleur66** [dg5lp/JTDX-Helper-2.1#6]
A great improvement would be to allow user to set QRG instead of band to allow "chasing" specific station which are using non standard QRG

Instead of 

```
160:00-0600,S/P,FT8,BEST-S/N
40:0600-0700,S/P,FT8,MOST-DISTANCE
6:0700-2400,S/P,FT8,PREFER-WANTED
```

we could 

```
1,836:00-0600,S/P,FT8,BEST-S/N
7,056:0600-0700,S/P,FT8,MOST-DISTANCE
6m:0700-2400,S/P,FT8,PREFER-WANTED
```

In this exemple, I can set 1836Khz between 00:00z and at 07:00z I switch on regular 6m band

**Comment by dg5lp** [comment]
Sorry, it is not possible.  The Helper has no possibility to change the QRG, it can only select pre-defined frequencies.

 

If you want to use non-standard QRGs,  enter it into JTDX. The new frequency will be shown in the selection menu

of JTDX. E.g. you will work on 7,056/FT8 instead of 7,074.  Check the position in the selection menu, e.g. 4th. position.

Add the new band into the Helper`s band list. The band name can you choose as you want, in this case it could be 41.

 

The band list in the Helper should be: 160 80 60 41 40 …  30 

You can then select 

41:0600-0700,S/P,FT8,MOST-DISTANCE
 
The Helper does not check the band value, it selects the 4.th entry from the selection list.
On this reason it is important that the band list is in accordance with the selection list in JTDX.
Please note, that the frequency order in JTDX must be identical in FT4 and FT8. If you add a new for FT8,
you should add it for FT4 too, even if it not used

 

 

Von: Toucouleur66 ***@***.*** 
Gesendet: Dienstag, 11. April 2023 08:23
An: dg5lp/JTDX-Helper-2.6
Cc: Subscribed
Betreff: [dg5lp/JTDX-Helper-2.6] Set frequency instead of band while using band hoping (Issue #6)

 

A great improvement would be to allow user to set QRG instead of band to allow "chasing" specific station which are using non standard QRG

Instead of

160:00-0600,S/P,FT8,BEST-S/N
40:0600-0700,S/P,FT8,MOST-DISTANCE
6:0700-2400,S/P,FT8,PREFER-WANTED

we could

1,836:00-0600,S/P,FT8,BEST-S/N
7,056:0600-0700,S/P,FT8,MOST-DISTANCE
6m:0700-2400,S/P,FT8,PREFER-WANTED

In this exemple, I can set 1836Khz between 00:00z and at 07:00z I switch on regular 6m band
